#!/bin/bash
 
. ../common_OSX.sh

function printHelp ()
{
    printHeader
    echo ""
    echo -e "${RESET} options for this exec are: "
    echo -e "${GREEN}-h ${RESET}Print this help information" | indent
    echo -e "${GREEN}-n ${RESET}defaults to ${GREEN}zerotoblockchain-network${RESET}. use ${YELLOW}-n your-named-network ${RESET}if you are using a different network name"  | indent
    echo -e "\t\tyou will have to ensure that the name you use here is also the name you use in BOTH package.json files and in your application code" | indent
    echo ""
    echo ""
}

# print the header information for execution
function printHeader ()
{
    echo ""
    echo -e "${YELLOW}network archive, start and deploy script for the Zero To Blockchain Series" | indent
    echo -e "${GREEN}This has been tested on Mac OSX thru High Sierra and Ubuntu V16 LTS" | indent
    echo -e "${YELLOW}This script will create your Composer archive" | indent
    echo ""
}
# get the command line options

NETWORK_NAME="zerotoblockchain-network"

 while getopts "h:n:" opt; 
do
    case "$opt" in
        h|\?)
        printHelp
        exit 0
        ;;
        n)  showStep "option passed for network name is: '$OPTARG'" 
            if [[ $OPTARG != "" ]]; then 
                NETWORK_NAME=$OPTARG 
            fi
        ;;
    esac
 done

printHeader
echo  "Parameters:"
echo -e "Network Name is: ${GREEN} $NETWORK_NAME ${RESET}" | indent

showStep "creating archive"
./createArchive.sh -n $NETWORK_NAME
showStep "starting network"
./startup.sh
showStep "deploying network"
./deployNetwork.sh -n $NETWORK_NAME
showStep "preserving admin cards for npm start processing"
SOURCE_DIR='controller/restapi/features/composer/creds'
BIZ_ADMIN='admin@zerotoblockchain-network'
NET_ADMIN='PeerAdmin@hlfv1'
if [[ ! -d $SOURCE_DIR/cards ]]; then
    mkdir $SOURCE_DIR/cards
fi
if [[ ! -d $SOURCE_DIR/client-data ]]; then
    mkdir $SOURCE_DIR/client-data
fi
cp -r $HOME/.composer/cards/$BIZ_ADMIN/ $SOURCE_DIR/cards/$BIZ_ADMIN/
cp -r $HOME/.composer/cards/$NET_ADMIN/ $SOURCE_DIR/cards/$NET_ADMIN/
cp -r $HOME/.composer/client-data/$BIZ_ADMIN/ $SOURCE_DIR/client-data/$BIZ_ADMIN/
cp -r $HOME/.composer/client-data/$NET_ADMIN/ $SOURCE_DIR/client-data/$NET_ADMIN/
